### ISSUE TITLE
Registry Path needs to be updated to use correct path.

### ISSUE THREAD

**Issue by tlor-cpts** [kevincobain2000/gobrew#20]
![image](https://user-images.githubusercontent.com/54855193/151444523-d0f8125b-a6dd-4de1-bf74-728e1a826aeb.png)

Issue is current path `registryPath`  of `https://golang.org/dl/` does not finish downloading as it fails due to incorrect path to the install package.  Path needs to be updated to use `https://go.dev/dl/` which is the updated path for downloading a version.

Does not install the correct windows package.

**Comment by kevincobain2000** [comment]
Oh thanks for reporting. I will test and update soon

**Comment by kevincobain2000** [comment]
Hi
So the registry url is correct but for windows, instead of tar, it is zip

Example:
*URL:* https://go.dev/dl/go1.17.6.windows-amd64.zip

*Screenshot:*

![Screen Shot 2022-01-28 at 21 37 12](https://user-images.githubusercontent.com/629055/151548186-40f988ad-34ef-4db9-ba9c-9f2ecc75b1a8.png)


--
Changing it from tar to zip based on version.
https://github.com/kevincobain2000/gobrew/blob/ca441946da4d7197205ba23874b9ef14d5732b14/gobrew.go#L343

and then here to unzip

https://github.com/kevincobain2000/gobrew/blob/ca441946da4d7197205ba23874b9ef14d5732b14/gobrew.go#L358-L363

However, I have never tested this library on Windows, I don't own a Windows machine to test it. I am pretty sure just those two will solve the installation issue on windows.

If you can submit a pull req I am happy to merge it for windows.

```
╰─$ go run cmd/gobrew/main.go install 1.17.1
[Info] Downloading version: 1.17.1
[Info] Downloading url: https://golang.org/dl/go1.17.1.darwin-amd64.tar.gz
[Success] Untar to /Users/pulkit.kathuria/.gobrew/versions/1.17.1
[Success] Downloaded version: 1.17.1
```

**Comment by tlor-cpts** [comment]
Hi,

That’s good to know.  How does the logic know which one is the right one to download?

-Tou

**Comment by tlor-cpts** [comment]
Let me try it out.

**Comment by kevincobain2000** [comment]
Closing to stay happy and sleep well.
