### ISSUE TITLE
cannot find my installed go

### ISSUE THREAD

**Issue by avary** [kevincobain2000/gobrew#211]
hello, just installed your tool on my old mac(high sierra 10.13), it failed to find installed go. 
❯ gobrew

GO Installed Version ....... None
GO go.mod Version    ....... 1.22 (not latest)
GO Latest Version    ....... 1.23.1

GO is not installed.
Do you want to use latest GO version (1.23.1)? [y/n]: n
❯ which go
/usr/local/bin/go 
❯ go version
go version go1.22.5 darwin/amd64

**Comment by kevincobain2000** [comment]
What’s your echo $PATH?

**Comment by avary** [comment]
/Users/adam/.gobrew/current/bin /Users/adam/.gobrew/bin /usr/local/bin /usr/local/sbin /opt/local/bin /opt/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin /Users/adam/.cargo/bin /Users/adam/go/bin /usr/local/opt/go/libexec/bin /Users/adam/go/bin ~/.composer/vendor/bin

**Comment by kevincobain2000** [comment]
Check if gobrew is correctly set up in your `$PATH`

Your gobrew directories (`/Users/adam/.gobrew/current/bin` and `/Users/adam/.gobrew/bin`) should be placed before `/usr/local/bin` in the `$PATH` so that the Go installed by gobrew takes precedence over the system Go version.

Modify the `.bashrc`, `.zshrc`, or equivalent shell configuration file:

Open the shell configuration file (e.g., `~/.zshrc` or `~/.bashrc`) and add the following lines, making sure they appear before any other Go paths:

```
export PATH="/Users/adam/.gobrew/current/bin:/Users/adam/.gobrew/bin:$PATH"
```

**Comment by the1337beauty** [comment]
I had this same problem.

Ended up installing a fresh go version using gobrew but I don't like that it doesn't start with my system version

**Comment by kevincobain2000** [comment]
Thanks @the1337beauty 
But there is nothing we can do to help it.
As long as the PATHs are in order, it is ok. And PATHs are different for each person on their envs.
