### ISSUE TITLE
bug: index out of range

### ISSUE THREAD

**Issue by juev** [kevincobain2000/gobrew#45]
https://github.com/kevincobain2000/gobrew/runs/7720193596
https://github.com/kevincobain2000/gobrew/runs/7720193909

```plain
Run gobrew use dev-latest
[Info]: Fetching remote versions
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/kevincobain2000/gobrew.(*GoBrew).judgeVersion(0xc000020125?, {0x7ffeefbfecbb, 0xa})
	/home/runner/work/gobrew/gobrew/gobrew.go:383 +0x7b4
github.com/kevincobain2000/gobrew.(*GoBrew).Install(0xc00010fef0, {0x7ffeefbfecbb?, 0xc000020318?})
	/home/runner/work/gobrew/gobrew/gobrew.go:317 +0x98
main.main()
	/home/runner/work/gobrew/gobrew/cmd/gobrew/main.go:60 +0xda
Error:  Cannot unmarshal data: json: cannot unmarshal object into Go value of type []gobrew.Tag
Error: Process completed with exit code 2.
```

**Comment by juev** [comment]
Checked many times. We have isolated cases when http request do not return anything.

**Comment by juev** [comment]
One more:
```json
{"message":"API rate limit exceeded for <redacted>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by kevincobain2000** [comment]
Yea, it is happening due to ratelimit.

```
╭─pulkit.kathuria@P84760 ~/git/dev-classified-server ‹master●›
╰─$ while true; do curl https://api.github.com/repos/golang/go/git/refs/tags;done                                              130 ↵
{"message":"API rate limit exceeded for 133.237.92.81. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
{"message":"API rate limit exceeded for 133.237.92.81. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

As a solution I am thinking about adding a crontab to this repo to update a json response, lets say in a file `golang-version-tags.json`
And instead of api, use https://raw.githubusercontent.com/kevincobain2000/gobrew/master/golang-version-tags.json 

https://github.com/kevincobain2000/gobrew/blob/dd4d8b2880d172a5f7124849956a146a6889e879/gobrew.go#L575

**Comment by kevincobain2000** [comment]
Yea, it is happening due to ratelimit.

```
╭─pulkit.kathuria@P84760 ~/git/dev-classified-server ‹master●›
╰─$ while true; do curl https://api.github.com/repos/golang/go/git/refs/tags;done                                              130 ↵
{"message":"API rate limit exceeded for xxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
{"message":"API rate limit exceeded for xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

As a solution I am thinking about adding a crontab to this repo to update a json response, lets say in a file `golang-version-tags.json`
And instead of api, use https://raw.githubusercontent.com/kevincobain2000/gobrew/master/golang-version-tags.json 

https://github.com/kevincobain2000/gobrew/blob/dd4d8b2880d172a5f7124849956a146a6889e879/gobrew.go#L575

**Comment by juev** [comment]
Its good idea, but we use Github Tags not only for golang/go, but for gobrew the self (for updating).

Maybe store this files not in repository? But in wiki, or gists?

**Comment by kevincobain2000** [comment]
gobrew self-update is fine to keep using gGthub tags, because it is not a feature used if gobrew is to be used by Github.
actions.

About storing the JSON file, it is ok to do it on gist but it is better to keep it inside this repo and use crontab to be all in one place. If you are worried about the unnecessary commits, then it can also be done via an orphan branch, for example: Idk branch name:`json` or `data` or `sync`.
